package com.secureqr.scanner.ui.vault;
import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.text.InputType;import android.text.method.PasswordTransformationMethod;import android.view.*;import android.widget.*;import androidx.fragment.app.FragmentActivity;import com.secureqr.scanner.R;import com.secureqr.scanner.security.SensitiveActionGuard;
final class VaultFormComponents{
 static EditText secret(Context c,String hint,String value,LinearLayout parent){return secret((FragmentActivity)c,hint,value,parent);}
 static LinearLayout section(Context c,String title,int icon){LinearLayout card=new LinearLayout(c);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(c,14),dp(c,10),dp(c,14),dp(c,14));GradientDrawable bg=new GradientDrawable();bg.setColor(c.getColor(R.color.card_background));bg.setCornerRadius(dp(c,12));bg.setStroke(dp(c,1),c.getColor(R.color.card_stroke));card.setBackground(bg);LinearLayout head=new LinearLayout(c);head.setGravity(Gravity.CENTER_VERTICAL);ImageView iv=new ImageView(c);iv.setImageResource(icon);int color=sectionIconColor(c,icon);iv.setImageTintList(android.content.res.ColorStateList.valueOf(color));GradientDrawable iconBg=new GradientDrawable();iconBg.setShape(GradientDrawable.OVAL);iconBg.setColor((color&0x00FFFFFF)|0x24000000);iv.setBackground(iconBg);iv.setPadding(dp(c,6),dp(c,6),dp(c,6),dp(c,6));head.addView(iv,new LinearLayout.LayoutParams(dp(c,32),dp(c,32)));TextView tv=new TextView(c);tv.setText(title);tv.setTextSize(15);tv.setTextColor(c.getColor(R.color.text_main));tv.setTypeface(null,1);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,dp(c,38),1);tp.setMarginStart(dp(c,9));head.addView(tv,tp);card.addView(head);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(c,10));card.setLayoutParams(cp);return card;}
 private static int sectionIconColor(Context c,int icon){if(icon==R.drawable.ic_key_line)return c.getColor(R.color.vault_icon_purple);if(icon==R.drawable.ic_link)return c.getColor(R.color.vault_icon_green);if(icon==R.drawable.ic_edit_24)return c.getColor(R.color.vault_icon_orange);if(icon==R.drawable.ic_history)return c.getColor(R.color.vault_icon_yellow);if(icon==R.drawable.ic_vault_attachment||icon==R.drawable.ic_vault_photo||icon==R.drawable.ic_vault_contract)return c.getColor(R.color.vault_icon_cyan);if(icon==R.drawable.ic_vault_card||icon==R.drawable.ic_vault_wallet||icon==R.drawable.ic_vault_payment)return c.getColor(R.color.vault_icon_orange);if(icon==R.drawable.ic_vault_certificate||icon==R.drawable.ic_vault_license)return c.getColor(R.color.vault_icon_purple);if(icon==R.drawable.ic_shield||icon==R.drawable.ic_vault_identity)return c.getColor(R.color.vault_icon_blue);if(icon==R.drawable.ic_vault_car)return c.getColor(R.color.vault_icon_green);return c.getColor(R.color.vault_icon_cyan);}
 static LinearLayout field(Context c,String label){LinearLayout box=new LinearLayout(c);box.setOrientation(LinearLayout.VERTICAL);TextView l=new TextView(c);l.setText(label);l.setTextSize(12);l.setTextColor(c.getColor(R.color.text_secondary));box.addView(l,new LinearLayout.LayoutParams(-1,dp(c,25)));return box;}
 static EditText text(Context c,String hint,String value,boolean multiline){EditText e=new EditText(c);e.setHint(hint);e.setText(value);e.setTextSize(14);e.setTextColor(c.getColor(R.color.text_main));e.setHintTextColor(c.getColor(R.color.text_hint));e.setBackgroundResource(R.drawable.bg_edit_text);e.setPadding(dp(c,11),multiline?dp(c,9):0,dp(c,11),multiline?dp(c,9):0);e.setGravity(multiline?Gravity.TOP|Gravity.START:Gravity.CENTER_VERTICAL);e.setSingleLine(!multiline);e.setMinLines(multiline?4:1);e.setInputType(InputType.TYPE_CLASS_TEXT|(multiline?InputType.TYPE_TEXT_FLAG_MULTI_LINE:0));return e;}
 static EditText secret(FragmentActivity c,String hint,String value,LinearLayout parent){LinearLayout row=new LinearLayout(c);row.setGravity(Gravity.CENTER_VERTICAL);row.setBackgroundResource(R.drawable.bg_edit_text);EditText e=new EditText(c);e.setHint(hint);e.setText(value);e.setSingleLine(true);e.setTextSize(14);e.setPadding(dp(c,11),0,0,0);e.setBackgroundColor(Color.TRANSPARENT);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);e.setTransformationMethod(PasswordTransformationMethod.getInstance());row.addView(e,new LinearLayout.LayoutParams(0,dp(c,46),1));ImageButton eye=iconButton(c,R.drawable.ic_visibility_off_24,c.getString(R.string.vault_secret_toggle));eye.setOnClickListener(v->{boolean hidden=e.getTransformationMethod() instanceof PasswordTransformationMethod;if(!hidden){e.setTransformationMethod(PasswordTransformationMethod.getInstance());eye.setImageResource(R.drawable.ic_visibility_off_24);e.setSelection(e.length());return;}SensitiveActionGuard.requireRecentAuth(c,c.getString(R.string.vault_sensitive_view_reason),()->{e.setTransformationMethod(null);eye.setImageResource(R.drawable.ic_visibility_24);e.setSelection(e.length());});});row.addView(eye);ImageButton copy=iconButton(c,R.drawable.ic_content_copy_24,c.getString(R.string.common_action_copy));copy.setOnClickListener(v->SensitiveActionGuard.requireRecentAuth(c,c.getString(R.string.vault_sensitive_copy_reason),()->{((android.content.ClipboardManager)c.getSystemService(Context.CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("KeyScan",e.getText()));Toast.makeText(c,R.string.vault_copied,Toast.LENGTH_SHORT).show();}));row.addView(copy);parent.addView(row,new LinearLayout.LayoutParams(-1,dp(c,46)));return e;}
 static Button attachment(Context c,String label){Button b=new Button(c);b.setText(c.getString(R.string.vault_choose_attachment,label));b.setTextColor(c.getColor(R.color.action_icon_tint));return b;}
 private static ImageButton iconButton(Context c,int icon,String desc){ImageButton b=new ImageButton(c);b.setImageResource(icon);b.setImageTintList(android.content.res.ColorStateList.valueOf(c.getColor(R.color.text_secondary)));b.setBackgroundColor(Color.TRANSPARENT);b.setContentDescription(desc);b.setPadding(dp(c,8),dp(c,8),dp(c,8),dp(c,8));b.setLayoutParams(new LinearLayout.LayoutParams(dp(c,42),dp(c,42)));return b;}static int dp(Context c,int n){return(int)(n*c.getResources().getDisplayMetrics().density+.5f);}private VaultFormComponents(){}
}
