package com.secureqr.scanner.ui.vault;

import android.content.res.ColorStateList;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import androidx.annotation.NonNull;import androidx.fragment.app.Fragment;import androidx.recyclerview.widget.*;import com.google.android.material.bottomsheet.BottomSheetDialog;import com.secureqr.scanner.R;import com.secureqr.scanner.vault.VaultTypes;import java.util.*;

public final class VaultNavigation{
 public static void showTypePicker(Fragment f){showSheet(f,null);}
 public static void showTypePicker(Fragment f,String category){showSheet(f,VaultTypes.category(category));}
 private static void showSheet(Fragment f,VaultTypes.Category initial){BottomSheetDialog d=new BottomSheetDialog(f.requireContext());View root=f.getLayoutInflater().inflate(R.layout.bottom_sheet_vault_create,null);d.setContentView(root);TextView title=root.findViewById(R.id.tv_sheet_title),subtitle=root.findViewById(R.id.tv_sheet_subtitle);ImageButton back=root.findViewById(R.id.btn_sheet_back);RecyclerView list=root.findViewById(R.id.recycler_sheet_create);list.setLayoutManager(new LinearLayoutManager(f.requireContext()));ChoiceAdapter adapter=new ChoiceAdapter(f,d);list.setAdapter(adapter);Runnable categories=()->{title.setText(R.string.vault_create_title);subtitle.setText(R.string.vault_create_choose_type);back.setVisibility(View.GONE);adapter.showCategories();};back.setOnClickListener(v->categories.run());root.findViewById(R.id.btn_sheet_close).setOnClickListener(v->d.dismiss());adapter.onCategory=c->{title.setText(f.getString(R.string.vault_create_category_title,f.getString(c.labelRes)));subtitle.setText(R.string.vault_create_choose_specific_type);back.setVisibility(View.VISIBLE);adapter.showTypes(c);};if(initial==null)categories.run();else{title.setText(f.getString(R.string.vault_create_category_title,f.getString(initial.labelRes)));subtitle.setText(R.string.vault_create_choose_specific_type);back.setVisibility(View.VISIBLE);adapter.showTypes(initial);}d.setOnShowListener(x->{View sheet=d.findViewById(com.google.android.material.R.id.design_bottom_sheet);if(sheet!=null)com.google.android.material.bottomsheet.BottomSheetBehavior.from(sheet).setState(com.google.android.material.bottomsheet.BottomSheetBehavior.STATE_EXPANDED);});d.show();}
 private interface CategoryClick{void click(VaultTypes.Category c);}
 private static final class Choice{VaultTypes.Category category;VaultTypes.Type type;String title,summary;int icon,color;}
 private static final class ChoiceAdapter extends RecyclerView.Adapter<ChoiceAdapter.H>{final Fragment f;final BottomSheetDialog dialog;final List<Choice> data=new ArrayList<>();CategoryClick onCategory;ChoiceAdapter(Fragment f,BottomSheetDialog d){this.f=f;dialog=d;}void showCategories(){data.clear();for(VaultTypes.Category c:VaultTypes.CATEGORIES){Choice x=new Choice();x.category=c;x.title=f.getString(c.labelRes);x.summary=f.getString(categorySummary(c.key));x.icon=categoryIcon(c.key);x.color=categoryColor(c.key);data.add(x);}notifyDataSetChanged();}void showTypes(VaultTypes.Category c){data.clear();for(VaultTypes.Type t:c.types){Choice x=new Choice();x.type=t;x.title=f.getString(t.labelRes);x.summary=f.getString(typeSummary(t.key));x.icon=typeIcon(t.key);x.color=typeColor(t.key);data.add(x);}notifyDataSetChanged();}@NonNull public H onCreateViewHolder(@NonNull ViewGroup p,int v){return new H(LayoutInflater.from(p.getContext()).inflate(R.layout.item_vault_create_choice,p,false));}public void onBindViewHolder(@NonNull H h,int p){Choice x=data.get(p);h.title.setText(x.title);h.summary.setText(x.summary);h.icon.setImageResource(x.icon);if(x.category!=null){GradientDrawable bg=new GradientDrawable();bg.setColor(h.itemView.getContext().getColor(x.color));bg.setCornerRadius(h.itemView.getResources().getDisplayMetrics().density*8);h.icon.setBackground(bg);h.icon.setImageTintList(ColorStateList.valueOf(Color.WHITE));}else{h.icon.setBackground(null);h.icon.setImageTintList(ColorStateList.valueOf(h.itemView.getContext().getColor(x.color)));}h.itemView.setOnClickListener(v->{if(x.category!=null)onCategory.click(x.category);else{dialog.dismiss();f.getParentFragmentManager().beginTransaction().replace(R.id.fragment_container,VaultEditFragment.newItem(x.type.key)).addToBackStack(null).commit();}});}public int getItemCount(){return data.size();}static final class H extends RecyclerView.ViewHolder{ImageView icon;TextView title,summary;H(View v){super(v);icon=v.findViewById(R.id.iv_choice_icon);title=v.findViewById(R.id.tv_choice_title);summary=v.findViewById(R.id.tv_choice_summary);}}}
 private static int categorySummary(String k){if(VaultTypes.KEYS.equals(k))return R.string.vault_category_summary_keys;if(VaultTypes.IDENTITY.equals(k))return R.string.vault_category_summary_identity;if(VaultTypes.FINANCIAL.equals(k))return R.string.vault_category_summary_financial;if(VaultTypes.CONTACT.equals(k))return R.string.vault_category_summary_contact;if(VaultTypes.FILES.equals(k))return R.string.vault_category_summary_files;return R.string.vault_category_summary_custom;}
 private static int categoryIcon(String k){if(VaultTypes.KEYS.equals(k))return R.drawable.ic_key_line;if(VaultTypes.IDENTITY.equals(k))return R.drawable.ic_vault_identity;if(VaultTypes.FINANCIAL.equals(k))return R.drawable.ic_vault_wallet;if(VaultTypes.CONTACT.equals(k))return R.drawable.ic_vault_mail;if(VaultTypes.FILES.equals(k))return R.drawable.ic_vault_file_lock;return R.drawable.ic_vault_gear;}
 private static int categoryColor(String k){if(VaultTypes.KEYS.equals(k))return R.color.vault_icon_blue;if(VaultTypes.IDENTITY.equals(k))return R.color.vault_icon_green;if(VaultTypes.FINANCIAL.equals(k))return R.color.vault_icon_orange;if(VaultTypes.CONTACT.equals(k))return R.color.vault_icon_purple;if(VaultTypes.FILES.equals(k))return R.color.vault_icon_cyan;return R.color.vault_icon_yellow;}
 private static int typeIcon(String k){switch(k){case"SOFTWARE_LICENSE":return R.drawable.ic_vault_license;case"SSH_KEY":return R.drawable.ic_key_line;case"API_KEY":return R.drawable.ic_vault_code;case"ACCESS_TOKEN":return R.drawable.ic_vault_tag;case"CERTIFICATE":return R.drawable.ic_vault_certificate;case"PASSPORT":return R.drawable.ic_vault_passport;case"DRIVER_LICENSE":case"US_DRIVER_LICENSE":return R.drawable.ic_vault_car;case"SOCIAL_SECURITY":return R.drawable.ic_vault_number;case"NATIONAL_ID":case"MY_NUMBER_CARD":case"PERSONALAUSWEIS":case"FRANCE_CNI":case"KOREA_ID":case"CANADA_ID":case"AUSTRALIA_ID":case"OTHER_ID":return R.drawable.ic_vault_identity;case"BANK_CARD":return R.drawable.ic_vault_card;case"CRYPTO_WALLET":return R.drawable.ic_vault_wallet;case"PAYMENT":return R.drawable.ic_vault_payment;case"EMAIL":return R.drawable.ic_vault_mail;case"CONTACT_INFO":case"OTHER_CONTACT":return R.drawable.ic_vault_contact;case"ID_PHOTO":return R.drawable.ic_vault_photo;case"CONTRACT":case"IMPORTANT_DOCUMENT":return R.drawable.ic_vault_contract;case"OTHER_ATTACHMENT":return R.drawable.ic_vault_attachment;default:return R.drawable.ic_vault_gear;}}
 private static int typeColor(String k){switch(k){case"SSH_KEY":case"ID_PHOTO":case"CONTRACT":case"IMPORTANT_DOCUMENT":case"OTHER_ATTACHMENT":return R.color.vault_icon_cyan;case"ACCESS_TOKEN":case"EMAIL":case"CONTACT_INFO":case"OTHER_CONTACT":return R.color.vault_icon_purple;case"CERTIFICATE":case"NATIONAL_ID":case"PASSPORT":case"DRIVER_LICENSE":case"US_DRIVER_LICENSE":case"MY_NUMBER_CARD":case"PERSONALAUSWEIS":case"FRANCE_CNI":case"KOREA_ID":case"CANADA_ID":case"AUSTRALIA_ID":case"OTHER_ID":return R.color.vault_icon_green;case"BANK_CARD":case"CRYPTO_WALLET":case"PAYMENT":return R.color.vault_icon_orange;case"SOCIAL_SECURITY":case"CUSTOM":return R.color.vault_icon_yellow;default:return R.color.vault_icon_blue;}}
 private static int typeSummary(String k){switch(k){case"SOFTWARE_LICENSE":return R.string.vault_type_summary_software_license;case"SSH_KEY":return R.string.vault_type_summary_ssh_key;case"API_KEY":return R.string.vault_type_summary_api_key;case"ACCESS_TOKEN":return R.string.vault_type_summary_access_token;case"CERTIFICATE":return R.string.vault_type_summary_certificate;case"PASSPORT":return R.string.vault_type_summary_passport;case"NATIONAL_ID":return R.string.vault_type_summary_national_id;case"DRIVER_LICENSE":return R.string.vault_type_summary_driver_license;case"SOCIAL_SECURITY":return R.string.vault_type_summary_social_security;case"BANK_CARD":return R.string.vault_type_summary_bank_card;case"CRYPTO_WALLET":return R.string.vault_type_summary_crypto_wallet;case"EMAIL":return R.string.vault_type_summary_email;case"MAIL_CONFIG":return R.string.vault_type_summary_mail_config;case"CONTACT_INFO":return R.string.vault_type_summary_contact_info;case"ID_PHOTO":return R.string.vault_type_summary_id_photo;case"KEY_FILE":return R.string.vault_type_summary_key_file;case"CONTRACT":return R.string.vault_type_summary_contract;case"CUSTOM_ATTACHMENT":return R.string.vault_type_summary_attachment;default:return R.string.vault_type_summary_custom;}}
 private VaultNavigation(){}
}
