package com.secureqr.scanner.ui.vault;
import android.content.Context;import com.secureqr.scanner.R;import com.secureqr.scanner.vault.VaultTypes;import java.util.*;
final class VaultFormSchema{
 enum Kind{TEXT,SECRET,MULTILINE,DATE,ATTACHMENT}
 static final class Field{final String key,label,hint;final Kind kind;final String row;Field(String k,String l,String h,Kind t,String r){key=k;label=l;hint=h;kind=t;row=r;}}
 static final class Section{final String title;final int icon;final List<Field> fields=new ArrayList<>();Section(String t,int i){title=t;icon=i;}Section add(String k,String l,String h,Kind kind){fields.add(new Field(k,l,h,kind,null));return this;}Section pair(String k,String l,String h,String row){fields.add(new Field(k,l,h,Kind.TEXT,row));return this;}Section attach(String label){fields.add(new Field("@attachment",label,"",Kind.ATTACHMENT,null));return this;}}
 static List<Section> forType(VaultTypes.Type type){List<Section>s=new ArrayList<>();switch(type.key){
  case"SSH_KEY":s.add(sec("基本信息",R.drawable.ic_vault_identity).add("title","名称","例如：阿里云生产服务器",Kind.TEXT).add("label","标签（可选）","例如：生产环境 / Git连接",Kind.TEXT));s.add(sec("连接信息",R.drawable.ic_link).pair("server","服务器地址","例如：192.168.1.10","host").pair("port","端口","22","host").add("username","用户名","例如：root",Kind.TEXT));s.add(sec("认证信息",R.drawable.ic_key_line).add("password","密码（可选）","服务器登录密码",Kind.SECRET).add("passphrase","密码短语（可选）","SSH私钥保护密码短语",Kind.SECRET).attach("私钥文件").add("publicKey","公钥","粘贴公钥内容…",Kind.MULTILINE));break;
  case"API_KEY":s.add(sec("基本信息",R.drawable.ic_vault_identity).add("title","名称","例如：OpenAI生产环境Key",Kind.TEXT).add("service","服务商","OpenAI / AWS / GitHub / Google / Azure / 自定义",Kind.TEXT).add("label","标签（可选）","例如：AI / 开发 / 工作",Kind.TEXT));s.add(sec("服务信息",R.drawable.ic_link).add("apiAddress","API地址","例如：api.openai.com",Kind.TEXT).add("endpoint","Endpoint（可选）","例如：/v1/chat/completions",Kind.TEXT).add("docsUrl","文档地址（可选）","例如：https://platform.openai.com/docs",Kind.TEXT));s.add(sec("密钥信息",R.drawable.ic_key_line).add("apiKey","API Key", "输入 API Key",Kind.SECRET).add("secret","Secret Key（可选）","输入 Secret Key",Kind.SECRET));s.add(sec("有效期",R.drawable.ic_history).add("createdDate","创建时间","YYYY-MM-DD",Kind.DATE).add("expiryDate","过期时间","YYYY-MM-DD",Kind.DATE));break;
  case"SOFTWARE_LICENSE":s.add(sec("基本信息",R.drawable.ic_vault_license).add("title","名称","例如：Adobe Photoshop",Kind.TEXT).add("softwareName","软件名称","软件或产品名称",Kind.TEXT).add("email","授权邮箱","用于购买或激活的邮箱",Kind.TEXT));s.add(sec("许可信息",R.drawable.ic_vault_certificate).add("licenseNumber","许可证编号","输入许可证编号",Kind.SECRET).add("purchaseDate","购买日期","YYYY-MM-DD",Kind.DATE).attach("许可证文件"));break;
  case"ACCESS_TOKEN":s.add(sec("基本信息",R.drawable.ic_vault_tag).add("title","名称","例如：GitHub部署Token",Kind.TEXT).add("service","所属服务","例如：GitHub",Kind.TEXT).add("scope","权限范围","例如：repo, read:user",Kind.TEXT));s.add(sec("敏感信息",R.drawable.ic_key_line).add("token","Token","输入访问令牌",Kind.SECRET).add("expiryDate","过期时间","YYYY-MM-DD",Kind.DATE));break;
  case"CERTIFICATE":s.add(sec("基本信息",R.drawable.ic_vault_certificate).add("title","名称","证书名称",Kind.TEXT).add("expiryDate","有效期","YYYY-MM-DD",Kind.DATE));s.add(sec("证书文件",R.drawable.ic_vault_attachment).attach("选择证书或私钥文件"));break;
  case"PASSPORT":s.add(sec("基本信息",R.drawable.ic_vault_passport).add("title","名称","例如：本人护照",Kind.TEXT).add("fullName","姓名","证件姓名",Kind.TEXT));s.add(sec("证件信息",R.drawable.ic_vault_identity).add("passportNumber","护照号码","输入护照号码",Kind.SECRET).add("nationality","国籍","输入国籍",Kind.TEXT).add("birthDate","出生日期","YYYY-MM-DD",Kind.DATE).add("expiryDate","有效期限","YYYY-MM-DD",Kind.DATE).add("authority","签发机关","输入签发机关",Kind.TEXT));s.add(sec("附件",R.drawable.ic_vault_photo).attach("护照照片"));break;
  case"NATIONAL_ID":s.add(sec("基本信息",R.drawable.ic_vault_identity).add("title","名称","例如：本人身份证",Kind.TEXT).add("fullName","姓名","证件姓名",Kind.TEXT));s.add(sec("证件信息",R.drawable.ic_shield).add("documentNumber","身份证号码","输入证件号码",Kind.SECRET).add("birthDate","出生日期","YYYY-MM-DD",Kind.DATE).add("address","地址","输入证件地址",Kind.MULTILINE).add("authority","签发机关","输入签发机关",Kind.TEXT).add("expiryDate","有效期限","YYYY-MM-DD",Kind.DATE));s.add(sec("附件",R.drawable.ic_vault_photo).attach("身份证正面/背面照片"));break;
  case"DRIVER_LICENSE":s.add(sec("基本信息",R.drawable.ic_vault_car).add("title","名称","例如：本人驾驶证",Kind.TEXT).add("fullName","姓名","证件姓名",Kind.TEXT));s.add(sec("证件信息",R.drawable.ic_vault_identity).add("licenseNumber","驾驶证号码","输入证件号码",Kind.SECRET).add("licenseClass","准驾类型","例如：C1",Kind.TEXT).add("expiryDate","有效期限","YYYY-MM-DD",Kind.DATE).add("authority","签发机构","输入签发机构",Kind.TEXT));s.add(sec("附件",R.drawable.ic_vault_photo).attach("驾驶证正面/背面照片"));break;
  case"US_DRIVER_LICENSE":case"MY_NUMBER_CARD":case"PERSONALAUSWEIS":case"FRANCE_CNI":case"KOREA_ID":case"CANADA_ID":case"AUSTRALIA_ID":case"OTHER_ID":s.add(sec("基本信息",R.drawable.ic_vault_identity).add("title","名称","输入证件名称",Kind.TEXT).add("fullName","姓名","证件姓名",Kind.TEXT).add("documentType","证件类型",type.key,Kind.TEXT));s.add(sec("证件信息",R.drawable.ic_shield).add("documentNumber","证件号码","输入证件号码",Kind.SECRET).add("birthDate","出生日期","YYYY-MM-DD",Kind.DATE).add("country","国家/地区","输入国家或地区",Kind.TEXT).add("authority","签发机关","输入签发机关",Kind.TEXT).add("expiryDate","有效期限","YYYY-MM-DD",Kind.DATE));s.add(sec("附件",R.drawable.ic_vault_photo).attach("证件正面/背面照片"));break;
  case"BANK_CARD":s.add(sec("基本信息",R.drawable.ic_vault_card).add("title","名称","例如：工资卡",Kind.TEXT).add("bank","银行名称","输入发卡银行",Kind.TEXT).add("cardType","卡类型","借记卡 / 信用卡",Kind.TEXT).add("cardholder","持卡人","输入持卡人姓名",Kind.TEXT));s.add(sec("卡片信息",R.drawable.ic_vault_wallet).add("cardNumber","银行卡号","输入银行卡号",Kind.SECRET).add("expiryDate","有效期","例如：09/34",Kind.DATE));s.add(sec("敏感信息",R.drawable.ic_key_line).add("cvv","CVV安全码","输入CVV",Kind.SECRET).add("pin","PIN密码（可选）","输入PIN",Kind.SECRET).add("securityPassword","安全密码（可选）","输入安全密码",Kind.SECRET));s.add(sec("附件",R.drawable.ic_vault_photo).attach("银行卡图片"));break;
  case"CRYPTO_WALLET":s.add(sec("基本信息",R.drawable.ic_vault_wallet).add("title","钱包名称","例如：主要ETH钱包",Kind.TEXT).add("network","链类型","Ethereum / Bitcoin 等",Kind.TEXT).add("address","钱包地址","输入钱包地址",Kind.MULTILINE));s.add(sec("敏感信息",R.drawable.ic_key_line).add("seed","助记词","输入助记词",Kind.SECRET).attach("Keystore文件"));break;
  case"EMAIL":s.add(sec("基本信息",R.drawable.ic_vault_mail).add("title","名称","例如：工作邮箱",Kind.TEXT).add("email","邮箱地址","name@example.com",Kind.TEXT).add("provider","服务商","例如：Gmail",Kind.TEXT));break;
  case"MAIL_CONFIG":s.add(sec("基本信息",R.drawable.ic_vault_mail_settings).add("title","名称","邮箱配置名称",Kind.TEXT).add("email","邮箱地址","name@example.com",Kind.TEXT).add("username","用户名","登录用户名",Kind.TEXT));s.add(sec("服务器配置",R.drawable.ic_link).add("imap","IMAP服务器","imap.example.com",Kind.TEXT).add("smtp","SMTP服务器","smtp.example.com",Kind.TEXT));break;
  default:s.add(generic(type));break;}
  s.add(sec("备注",R.drawable.ic_edit_24).add("notes","备注","输入用途说明、备注或补充内容…",Kind.MULTILINE));return s;}
 private static Section generic(VaultTypes.Type t){Section s=sec("基本信息",typeIcon(t.key)).add("title","名称","输入资料名称",Kind.TEXT);for(VaultTypes.Field f:t.fields){if("name".equals(f.key)||"fullName".equals(f.key))continue;s.add(f.key,label(f),"输入"+label(f),f.secret?Kind.SECRET:("content".equals(f.key)||"address".equals(f.key)?Kind.MULTILINE:(f.date?Kind.DATE:Kind.TEXT)));}if(t.fields.isEmpty()||VaultTypes.IDENTITY.equals(t.category))s.attach(VaultTypes.IDENTITY.equals(t.category)?"证件图片":"选择附件");return s;}
 private static String label(VaultTypes.Field f){switch(f.key){case"fullName":return"姓名";case"number":return"号码";case"country":return"国家/地区";case"documentType":return"证件类型";case"documentNumber":return"证件号码";case"provider":return"服务商";case"account":return"账户";case"phone":return"电话";case"email":return"邮箱";case"address":return"地址";case"content":return"内容";default:return f.key.replaceAll("([A-Z])"," $1");}}
 private static Section sec(String t,int i){return new Section(t,i);}private static int typeIcon(String k){if("PAYMENT".equals(k))return R.drawable.ic_vault_payment;if("CONTACT_INFO".equals(k))return R.drawable.ic_vault_contact;if("ID_PHOTO".equals(k))return R.drawable.ic_vault_photo;if("CONTRACT".equals(k))return R.drawable.ic_vault_contract;if("CUSTOM_ATTACHMENT".equals(k))return R.drawable.ic_vault_attachment;return R.drawable.ic_vault_gear;}private VaultFormSchema(){}

 static String sectionTitle(Context c,Section s){switch(s.title){case"基本信息":return c.getString(R.string.vault_basic_info);case"连接信息":return c.getString(R.string.vault_section_connection);case"认证信息":return c.getString(R.string.vault_section_authentication);case"服务信息":return c.getString(R.string.vault_section_service);case"密钥信息":return c.getString(R.string.vault_section_keys);case"有效期":return c.getString(R.string.vault_section_validity);case"许可信息":return c.getString(R.string.vault_section_license);case"敏感信息":return c.getString(R.string.vault_section_sensitive);case"证书文件":return c.getString(R.string.vault_section_certificate_files);case"证件信息":return c.getString(R.string.vault_section_document);case"卡片信息":return c.getString(R.string.vault_section_card);case"服务器配置":return c.getString(R.string.vault_section_server_config);case"备注":return c.getString(R.string.vault_field_notes);default:return c.getString(R.string.vault_attachments);}}
 static String fieldLabel(Context c,Field f){if(f.kind==Kind.ATTACHMENT)return c.getString(R.string.vault_add_attachment);int id=fieldLabelRes(f.key);return id==0?f.key.replaceAll("([A-Z])"," $1"):c.getString(id);}
 static String fieldHint(Context c,Field f){if(f.kind==Kind.DATE)return c.getString(R.string.vault_hint_date);return c.getString(R.string.vault_hint_enter_field,fieldLabel(c,f));}
 private static int fieldLabelRes(String k){switch(k){case"title":return R.string.vault_field_name;case"label":return R.string.vault_field_label;case"server":return R.string.vault_field_server;case"port":return R.string.vault_field_port;case"username":return R.string.vault_field_username;case"password":return R.string.vault_field_password;case"passphrase":return R.string.vault_field_passphrase;case"publicKey":return R.string.vault_field_public_key;case"service":return R.string.vault_field_service;case"apiAddress":return R.string.vault_field_api_address;case"endpoint":return R.string.vault_field_endpoint;case"docsUrl":return R.string.vault_field_docs_url;case"apiKey":return R.string.vault_field_api_key;case"secret":return R.string.vault_field_secret;case"createdDate":return R.string.vault_field_created_date;case"expiryDate":return R.string.vault_field_expiry_date;case"softwareName":return R.string.vault_field_software_name;case"email":return R.string.vault_field_email;case"licenseNumber":return R.string.vault_field_license_number;case"purchaseDate":return R.string.vault_field_purchase_date;case"scope":return R.string.vault_field_scope;case"token":return R.string.vault_field_token;case"fullName":return R.string.vault_field_full_name;case"passportNumber":return R.string.vault_field_passport_number;case"nationality":return R.string.vault_field_nationality;case"birthDate":return R.string.vault_field_birth_date;case"authority":return R.string.vault_field_authority;case"documentNumber":return R.string.vault_field_document_number;case"address":return R.string.vault_field_address;case"documentType":return R.string.vault_field_document_type;case"country":return R.string.vault_field_country;case"bank":return R.string.vault_field_bank;case"cardType":return R.string.vault_field_card_type;case"cardholder":return R.string.vault_field_cardholder;case"cardNumber":return R.string.vault_field_card_number;case"cvv":return R.string.vault_field_cvv;case"pin":return R.string.vault_field_pin;case"securityPassword":return R.string.vault_field_security_password;case"network":return R.string.vault_field_network;case"seed":return R.string.vault_field_seed;case"provider":return R.string.vault_field_provider;case"imap":return R.string.vault_field_imap;case"smtp":return R.string.vault_field_smtp;case"notes":return R.string.vault_field_notes;case"licenseClass":return R.string.vault_field_license_class;default:return 0;}}
}
